# Linear Algebra review

###  Vector and Matrix Norms
### Special Matrices and Vectors
### Eigenvalues and Eigenvectos

In [3]:
import sys
import numpy as np
import sympy as sp

In [8]:
#print out vector
x = np.array((1,2,3))
print(x)
y = np.ones((3,3))
print(y)

[1 2 3]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
#indexing 
A = np.ones((5,5), dtype = np.float)
print(A)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
A[:,0] = 3
print(A)

[[3. 1. 1. 1. 1.]
 [3. 1. 1. 1. 1.]
 [3. 1. 1. 1. 1.]
 [3. 1. 1. 1. 1.]
 [3. 1. 1. 1. 1.]]


In [13]:
#for higher dimensions, simply add an index:
B = np.ones((5,5,5), dtype = np.int)

#asssign first row a new value
B[:,0,0] = 6
print(B)

[[[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[6 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [15]:
A = np.matrix([[1,2],[3,4]])
B = np.ones((2,2), dtype = np.int)
print('This is A:')
print(A)
print('This is B:')
print(B)

This is A:
[[1 2]
 [3 4]]
This is B:
[[1 1]
 [1 1]]


In [16]:
A = np.array(range(9))
A = A.reshape(3,3)
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Linearly dependent:
Suppose we have 3 vectors: vec1, vec2, vec3 which is:

In [15]:
vec1 = np.matrix([[1],[1],[1]])
vec2 = np.matrix([[1],[2],[3]])
vec3 = np.matrix([[-1],[1],[3]])

print ("1:",vec1)
print ("2:",vec2)
print ("3:",vec3)

1: [[1]
 [1]
 [1]]
2: [[1]
 [2]
 [3]]
3: [[-1]
 [ 1]
 [ 3]]


Are those 3 vectors independent?
1. Check if x1.vec1 + x2.vec2 + x3.vec3 = [[0],[0],[0]] has non trivial solution. The three vectors are independent ifand only if there are no free variables for system: Ind . x = 0 where Ind is:


In [28]:
Ind = np.matrix([[1,1,1],[1,2,3],[-1,1,3]])
print(Ind)
#RRef 
print("RREF: ")
sp.Matrix(Ind).rref()

[[ 1  1  1]
 [ 1  2  3]
 [-1  1  3]]
RREF: 


(Matrix([
 [1, 0, -1],
 [0, 1,  2],
 [0, 0,  0]]), (0, 1))

We have a free variable so there are not linearly independent!

Try to find linear dependence relation by solving x1.vec1 + x2.vec2 + x3.vec3 = [[0],[0],[0]]

As x3 is free above, so for any x3:
3x3.vec1 - 2x3.vec2 + x3.vec3 = [[0],[0],[0]]

# Diagonal Matrices:
### Di,j = 0 for all i != j

In [20]:
D = np.matrix([[1,0,0], [0,2,0],[0,0,3]])
print ('This is a Diagonal Matrices:')
print(D)

This is a Diagonal Matrices:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


### Note for diagonal matrices:

Diagonal matrices are useful because multiplying by a diagonal matrix is computationally efficient

For diag(v)x, we only need to scale each element xi by vi


In [29]:
D = np.matrix([[1,0,0], [0,2,0],[0,0,3]])
E = np.ones((3,3), dtype = np.int)
#D * E = {0: {0:1,1:1,2:1}, 1:{0:2,1:2,2:2}, 2:{0:3, 1:3, 2:3}}

print(D*E)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In some cases, computationally efficient algorithms are designed by restricting some matrices to be diagonal

Diagonal matrices do not need to be square


# Symmetric Matrices: 
### Symmetric matrix is any matrix that is equal to its transpose: $A = A^{T}$

In [31]:
S = np.matrix([[1,2,3],[2,3,4],[3,4,5]])
print(S)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


# The unit vector:
### A unit vector is a vector with unit norm: ||x||2 = 1

A unit vector can be obtained by normalizing any vector. 

Normalization is the proccess of diving a vector by its magnitude with produces a unit vector:

x = [1,1,1,1] => x/srqt(1^2 + 1^2 + 1^2 + 1^2)  = x/sqrt(4) = [1/2, 1/2, 1/2, 1/2] =>(This vector has magnitude of 1)


# Inverse Matrix:
A*A^-1 = A^-1*A = I where I is identity matrix

Identity matrix is : square matrix + 1 on the diagonal and 0 elsewhere

It is similar to the reciprocal for integers.

In [5]:
I = np.matrix([[1,0,0],[0,1,0],[0,0,1]])
print(I)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Orthogonality
### A vector x and a vector y are orthogonal to each other if x T y = 0
Intuitively, if two vectors are orthogonal and both vectors have a nonzero magnitude, they will be at a 90 degree angle to each other.

If two vectors are orthogonal and unit vectors, they are called orthonormal

# Least sequares
### Definition:

x^ is a least squares solution of the system Ax = b if x^ is such that Ax^ -b is as small as possible.

Find least suqares solution to Ax = b where :

In [4]:
A = np.matrix([[1,1],[-1,1],[0,0]])
B = np.matrix([[2],[1],[1]])
print ("A:", A)
print ("B:", B)

A: [[ 1  1]
 [-1  1]
 [ 0  0]]
B: [[2]
 [1]
 [1]]


Idea. Ax = b is consistent <=> b is in Col(A)

So if Ax = b is inconsistent we

- replace b with its projection ^b
onto Col(A),

- and solve A^x = ^ b.(consistent by construction!)

In [19]:
A1 = [[1,1],[-1,1],[0,0]]
B1 = [[2],[1],[1]]
def col(matrix, i):
    return [row[i] for row in matrix]

#column 1 of B ad A
print(col(B1,0))
print(col(A1,0))


[2, 1, 1]
[1, -1, 0]


Cols(A) are orthogonal, projection of b of b onto Col(A) is:

$b  = \dfrac{Col(B1,0) * col(A1,0)}{(Col(A1,0)^2}{Col(A1,0)}
  + \dfrac{Col(B1,0) * col(A1,1)}{(Col(A1,1)^2}{Col(A1,1)} = [[2],[1],[0]]
$

then x = [[1/2],[3/2]]

### Normal equations:
^x is a least squares solution of Ax = b <=> ATA^x = ATb

# QR decomposition
In general, to obtain A = QR:
- Gram-Schmidt on (columns of) A, to get (columns of) Q.
- Then $R = Q^{T}A$.

Find the QR decomposition of QR_matrix =

In [22]:
QRm = [[1,2,4],[0,0,5],[0,3,6]]
print("QRm:", QRm)

QRm: [[1, 2, 4], [0, 0, 5], [0, 3, 6]]


We apply Gram-Schmidt to the columns of A:

In [23]:
#See col function above.
q1 = col(QRm,0)
#q1 = np.matrix([[1],[0],[0]])
print("q1:", q1)

q1: [1, 0, 0]


$q2 = col(QRm,1) - <col(QRm,1), q1>.q1$ (3x1 matrix) 

$q3 = col(QRm,2) - <col(QRm,2), q1>*q1 - <col(QRm,2), q2>*q2$ (3x1 matrix)

$Q  = [q1, q2, q3]$ (3x3 matrix)

Q is a permutation matrix and so orthogonal. Q

Q has orthonormal columns so $Q^{T}Q = 1$ !

To find R in A = QR, note that $Q^{T}A = Q^{T}QR = R$.

# Eigenvalues and Eigenvectors

Breaking mathematical objects into their constituent parts!

We can decompose matrices in ways that reveals information about their functional properties that is not immediately obvious from the representaion of the matrix as an array of elements 

Matrix => { Eigenvectors, Eigenvalues }

### The eigenvector:
The eigenvector of a square matrix A is a nonzero vector v such that multiplication by A alters only the scale of v

Av = $\lambda$v: v is the eigenvector, $\lambda$ is a scalar, the eigenvalue corresponding to v

Each eigenvector has an eigenvalue. Eigenvector is a vector that can be multiply by matrix A but doesn't change orientation.

### Eigendecomposition:
If a matrix A has n linearly independent eigenvectors... We can form a martix V with one eigenvector per clumn and a vector 7 of all the eigenvalues.

The eigendecomposition of A is then given by:

$A = V*diag(\lambda)*V^{-1}$ where diag($\lambda$) is diagonal matrix, $V^{-1}$ = inverse matrix.

Ax = $\lambda$x <=> Ax - $\lambda$x = 0 <=> (A-$\lambda$I)x = 0

Example: Find eigenvectors and eigenvalues of A:

In [62]:
A = np.matrix([[3,2,3],[0,6,10],[0,0,2]])
print('A:', A)

A: [[ 3  2  3]
 [ 0  6 10]
 [ 0  0  2]]


det(A - $\lambda$ I) = (3 - $\lambda$I).(3 - $\lambda$I).(2 - $\lambda$I) 

So A has eigenvalues of 2,3,6

The eigenvalues of a triangular matrix are its diagonal entries: so we have corresponding eigenvectors:

$\lambda_1$ = 2: (A - $\lambda_1 I$)x = [[1,2,3],[0,4,10],[0,0,0]] * x = 0 => $x_1$ = [[2],[-5/2],[1]]

$\lambda_2$ = 3: (A - $\lambda_2 I$)x = [[0,2,3],[0,3,10],[0,0,-1]] * x = 0 => $x_2$ = [[1],[0],[0]]

$\lambda_3$ = 6: (A - $\lambda_3 I$)x = [[-3,2,3],[0,0,10],[0,0,-4]] * x = 0 => $x_3$ = [[2],[3],[0]]
 

### Eigendecomposition Properties

Not every matrix can be decomposed into eigenvalues and eigenvectors

A matrix is singular (the inverse does not exist) if any of the eigenvalues are zeros

A matrix whose eigenvalues are all positive is called positive definite

A matrix whose eigenvalues are all positive or zero is positive semidefinite

Similarly, a matrix whose eigenvalues are all negative is negative definite / negative or zero is negative semidefinite 

### Why eigendecomposition?
Eigenvalue decomposition is used in principle components analysis (PCA)

PCA is a statistical procedure that is used to convert a set of observations of possibly correlated variables into a set of values of linearly uncorrelated variables called principal components

In other words, PCA is a method of summarizing the data or compressing the data/